# Generated by Django 5.1.7 on 2025-03-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanas', '0002_alter_donacion_funder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campana',
            name='estado',
            field=models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=20),
        ),
    ]
